/**
 * explain.js
 *
 * Deterministic projection of a proof generated by algo.js. This module never
 * loads a puzzle corpus, FEN index, expected move, expected trace, or answer
 * table. It only summarizes the proof object produced by the live solver.
 */

const PIECE_NAMES = Object.freeze({ p: "pawn", n: "knight", b: "bishop", r: "rook", q: "queen", k: "king" });
const FILES = "abcdefgh";

function squareFromIndex(index) {
  if (!Number.isInteger(index) || index < 0 || index >= 64) return "";
  return `${FILES[index % 8]}${8 - Math.floor(index / 8)}`;
}

function pieceText(ref, article = false) {
  if (!ref) return article ? "the piece" : "piece";
  const name = PIECE_NAMES[ref.type] || "piece";
  const text = ref.square ? `${name} on ${ref.square}` : name;
  return article ? `the ${text}` : text;
}

function preferredReply(node) {
  return (node?.replies || []).find((reply) => reply.live && reply.child?.proved) || null;
}

function terminalOf(proof) {
  let node = proof?.node || null;
  let terminal = null;
  while (node) {
    if (node.terminal) terminal = node.terminal;
    node = preferredReply(node)?.child?.node || null;
  }
  return terminal;
}

function unique(items) {
  const seen = new Set();
  return (items || []).filter((item) => {
    const value = String(item || "").trim();
    if (!value || seen.has(value.toLowerCase())) return false;
    seen.add(value.toLowerCase());
    return true;
  });
}

function indicesFromRefs(refs) {
  const output = new Set();
  for (const ref of refs || []) {
    const square = String(ref?.square || "");
    if (!/^[a-h][1-8]$/.test(square)) continue;
    output.add((8 - Number(square[1])) * 8 + FILES.indexOf(square[0]));
  }
  return output;
}

function relevantIndices(node) {
  const output = indicesFromRefs([...(node?.targets || []), ...(node?.newAttacks || [])]);
  if (Number.isInteger(node?.move?.to)) output.add(node.move.to);
  return output;
}

function observationScore(node, observation) {
  const uses = new Set(node?.uses || []);
  const indices = relevantIndices(node);
  const moveFrom = node?.move?.from;
  const moveTo = node?.move?.to;
  const kind = observation?.kind;
  let score = 0;

  if (kind === "loose") {
    if (observation.index === moveTo) score += 120;
    else if (indices.has(observation.index)) score += 75;
    if (uses.has("loose")) score += 18;
    if (observation.side === "enemy") score += 8;
  } else if (kind === "sole_defender") {
    if (observation.defender === moveTo) score += 115;
    if (observation.index === moveTo || indices.has(observation.index)) score += 85;
    if (observation.defender === moveFrom && observation.index !== moveFrom) score += 25;
    if (observation.side === "enemy") score += 8;
  } else if (kind === "alignment") {
    const squares = observation.alignment?.squares || [];
    const intersections = squares.filter((index) => indices.has(index) || index === moveFrom).length;
    if (intersections >= 2) score += 95 + intersections * 10;
  } else if (kind === "pin") {
    const facts = observation.pin || {};
    if ([facts.attacker, facts.pinned, facts.king].filter((index) => indices.has(index) || index === moveFrom).length >= 2) score += 100;
    if (uses.has("pin")) score += 20;
  } else if (kind === "passed_pawn") {
    if ([moveFrom, moveTo].includes(observation.pawn?.index)) score += 100;
    if (uses.has("passed_pawn")) score += 35;
  } else if (kind === "restricted_mobility") {
    if (node?.features?.check || node?.features?.mate || node?.features?.mate_threat || uses.has("restricted_mobility")) score += 70;
  } else if (kind === "mate_in_1" && (node?.features?.mate || node?.features?.mate_threat)) {
    score += 100;
  } else if (kind === "in_check") {
    score += 50;
  }
  return score;
}

function relevantObservations(node, limit = 4) {
  return (node?.observations || [])
    .map((observation) => ({ observation, score: observationScore(node, observation) }))
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score || String(a.observation.predicate || a.observation.text).localeCompare(String(b.observation.predicate || b.observation.text)))
    .map((entry) => entry.observation)
    .filter((observation, index, array) => array.findIndex((item) => (item.predicate || item.text) === (observation.predicate || observation.text)) === index)
    .slice(0, limit);
}

function relevantPredicateLines(node) {
  return relevantObservations(node, 5).map((observation) => observation.predicate || observation.text);
}

function targetByType(node, type) {
  return [...(node?.targets || []), ...(node?.newAttacks || [])].find((target) => target?.type === type) || null;
}

function onePlyPredicates(node) {
  const f = node?.features || {};
  const output = [];
  if (f.mate) output.push("mate");
  else if (f.check) output.push("gives_check");
  if (f.capture) output.push(`captures(${node.move?.captured ? `${node.move.captured.type.toUpperCase()}@${node.move.captured.square}` : "target"})`);
  if (f.mate_threat) output.push("creates_mate_threat");
  if (f.fork) output.push("creates_fork");
  if (f.attacks_queen) output.push(`attacks(${targetByType(node, "q") ? `Q@${targetByType(node, "q").square}` : "queen"})`);
  if (f.attacks_rook) output.push(`attacks(${targetByType(node, "r") ? `R@${targetByType(node, "r").square}` : "rook"})`);
  if (f.new_pin_count) output.push("creates_pin");
  if (f.discovered_attack_max) output.push("opens_discovered_attack");
  if (f.promotion || (node?.uses || []).includes("passed_pawn")) output.push("promotion_threat");
  if (!output.length) output.push("preserves_visible_gain");
  return output;
}

function closureKey(reply) {
  if (reply.live) return `LIVE:${reply.move?.uci || reply.move?.san}`;
  return `${reply.closure?.rule || "CLOSED"}|${reply.closure?.witness || ""}`;
}

function groupedReplies(node) {
  const groups = [];
  const closed = new Map();
  for (const reply of node?.replies || []) {
    if (reply.live) {
      groups.push({ live: true, replies: [reply], rule: "LIVE", witness: "" });
      continue;
    }
    const key = closureKey(reply);
    if (!closed.has(key)) closed.set(key, []);
    closed.get(key).push(reply);
  }
  for (const replies of closed.values()) {
    groups.push({
      live: false,
      replies,
      rule: replies[0]?.closure?.rule || "CLOSE-ONE-PLY-TACTIC",
      witness: replies[0]?.closure?.witness || "the named witness",
      text: replies[0]?.closure?.text || "the reply is closed by the same tactical witness"
    });
  }
  return groups;
}

function moveClassLabel(replies, total) {
  const names = replies.map((reply) => reply.move.san);
  if (replies.length === total - 1 && total > 3) return `all other ${replies.length} legal replies`;
  if (names.length <= 4) return names.join(" and ");
  return `${names.slice(0, 3).join(", ")}, and ${names.length - 3} others`;
}

function traceReplyLines(node) {
  const total = node?.replies?.length || 0;
  const lines = [];
  for (const group of groupedReplies(node)) {
    if (group.live) {
      const reply = group.replies[0];
      lines.push(`REPLY ${reply.move.san}: ${reply.description || "forcing defense"} :: LIVE.`);
    } else {
      const label = moveClassLabel(group.replies, total);
      lines.push(`REPLY CLASS ${label}: ${group.text} :: CLOSED BY ${group.rule} WITH ${group.witness}.`);
    }
  }
  return lines;
}

function observationSentences(node) {
  const output = [];
  const move = node?.move || {};
  const f = node?.features || {};
  const relevant = relevantObservations(node, 5);
  const capturedLoose = relevant.find((observation) => observation.kind === "loose" && observation.index === move.to);

  if (move.captured) {
    output.push(capturedLoose
      ? `${pieceText(move.captured, true)} is loose and can be captured by ${pieceText(move.mover, true)}`
      : `${pieceText(move.mover, true)} can capture ${pieceText(move.captured, true)}`);
  }

  const queen = targetByType(node, "q");
  const rook = targetByType(node, "r");
  const minor = [...(node?.targets || []), ...(node?.newAttacks || [])].find((target) => ["n", "b"].includes(target?.type));
  if (f.check && queen) output.push(`the same move can check the king and attack the queen on ${queen.square}`);
  else if (f.check && rook) output.push(`the same move can check the king and attack the rook on ${rook.square}`);
  else if (f.attacks_queen && queen) output.push(`the move also attacks the queen on ${queen.square}`);
  else if (f.attacks_rook && rook) output.push(`the move also attacks the rook on ${rook.square}`);
  else if (f.fork && minor) output.push(`the move can attack two targets, including the ${pieceText(minor)}`);

  for (const observation of relevant) {
    if (observation === capturedLoose) continue;
    if (observation.kind === "loose" && observation.index === move.to && move.captured) continue;
    if (observation.kind === "checks") continue;
    output.push(observation.text);
  }

  if (f.discovered_attack_max && !output.some((line) => /line|discovered|open/i.test(line))) output.push("moving the piece opens a line attack");
  if (f.new_pin_count && node?.newPins?.length) {
    const pin = node.newPins[0];
    output.push(`${pieceText(pin.pinned, true)} can be pinned to ${pieceText(pin.king, true)}`);
  } else if (f.new_pin_count) {
    output.push("the move can create a pin");
  }
  if ((node?.uses || []).includes("passed_pawn") && !output.some((line) => /passed pawn/i.test(line))) output.push("the passed pawn can create an immediate promotion problem");

  return unique(output).slice(0, 3);
}

function dominantClosureWitness(node, predicate = () => true) {
  const counts = new Map();
  for (const reply of node?.replies || []) {
    if (reply.live || !predicate(reply.closure || {})) continue;
    const witness = String(reply.closure?.witness || "").trim();
    if (!witness || /^the (named|declared|available|secured)/i.test(witness)) continue;
    counts.set(witness, (counts.get(witness) || 0) + 1);
  }
  return [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0]?.[0] || "";
}

function actionHeading(node) {
  const kind = node?.terminal?.kind || "";
  const f = node?.features || {};
  const reply = preferredReply(node);
  if (!f.check && f.capture && reply?.move?.san?.includes("x") && reply.child?.node?.features?.capture) return "COMPARE";
  if (["mate_threat", "policy_boundary", "forcing_check"].includes(kind)) return "THREAT";
  if (node?.terminal && ["material", "promotion", "fork", "queen_trap", "bound_target", "mate"].includes(kind)) return "CASH";
  if (!f.check && !f.mate_threat && !f.fork && !f.attacks_queen && !f.new_pin_count && node?.terminal) return "CASH";
  return "THREAT";
}

function actionSentence(node) {
  const move = node?.move?.san || "the move";
  const f = node?.features || {};
  const reply = preferredReply(node);
  const queen = targetByType(node, "q");
  const rook = targetByType(node, "r");
  const target = node?.move?.captured;
  const terminalKind = node?.terminal?.kind || "";
  const mateWitness = dominantClosureWitness(node, (closure) => /MATE|MATING-NET/.test(closure.rule || "") || /#$/.test(closure.witness || ""));

  if (f.mate) return `${move} mates`;
  if (["mate_threat", "policy_boundary"].includes(terminalKind) && mateWitness) return `${move} preserves the mating net and threatens ${mateWitness}`;
  if (terminalKind === "policy_boundary") return `${move} completes the named forcing clamp`;
  if (f.check && f.reply_count === 1) return `${move} is a check with one legal reply`;
  if (f.check && f.capture && queen) return `${move} captures ${pieceText(target, true)}, checks, and attacks the queen on ${queen.square}`;
  if (f.check && f.capture && rook) return `${move} captures ${pieceText(target, true)}, checks, and attacks the rook on ${rook.square}`;
  if (f.check && f.fork) return `${move} checks and creates a fork`;
  if (f.check && f.capture) return `${move} captures ${pieceText(target, true)} with check`;
  if (f.check && f.attacks_queen) return `${move} checks while attacking the queen on ${queen?.square || "its square"}`;
  if (f.check) return `${move} is the most forcing check and carries the visible tactical theme forward`;
  if (f.mate_threat) return `${move} creates a direct mate threat`;
  if ((node?.uses || []).includes("passed_pawn")) return `${move} advances the passed pawn and creates a promotion clamp`;
  if (f.new_pin_count && node?.newPins?.length) return `${move} pins ${pieceText(node.newPins[0].pinned, true)} to ${pieceText(node.newPins[0].king, true)}`;
  if (f.fork && queen) return `${move} creates a fork that attacks the queen on ${queen.square}`;
  if (f.fork) return `${move} creates a fork`;
  if (f.attacks_queen && queen) return `${move} attacks the queen on ${queen.square}`;
  if (f.discovered_attack_max) return `${move} opens a discovered attack`;
  if (f.capture && reply?.move?.san?.includes("x")) return `${move} captures ${pieceText(target, true)} and invites ${reply.move.san}`;
  if (f.capture) return `${move} captures ${pieceText(target, true)}`;
  return `${move} preserves and converts the visible gain`;
}

function liveReplySentence(reply, isPreferred = false) {
  const description = String(reply?.description || "");
  let sentence;
  if (/captures the attacking piece/i.test(description)) sentence = `${reply.move.san} captures the attacking piece and must be searched`;
  else if (/gives check/i.test(description)) sentence = `${reply.move.san} gives a countercheck and must be searched`;
  else if (/moves a bound target/i.test(description)) sentence = `${reply.move.san} moves the threatened target and must be searched`;
  else sentence = `${reply.move.san} is a live defense and must be searched`;
  if (isPreferred) return sentence.replace("must be searched", "is the strongest defense");
  const child = reply?.child?.node;
  if (child?.terminal?.kind === "mate") return `${sentence}; ${child.move.san} mates`;
  if (child?.terminal?.kind === "mate_threat" || child?.terminal?.kind === "policy_boundary") return `${sentence}; ${child.move.san} preserves the mating threat`;
  if (child?.terminal) return `${sentence}; ${child.move.san} closes that branch`;
  if (child?.move?.san) return `${sentence}; the branch is answered by ${child.move.san}`;
  return sentence;
}

function closedReplySentence(group, total) {
  const rule = group.rule || "";
  const witness = group.witness || "the named witness";
  const label = moveClassLabel(group.replies, total);
  const isOtherClass = group.replies.length === total - 1 && total > 3;
  const subject = isOtherClass ? "the other legal replies" : label;
  const singular = !isOtherClass && group.replies.length === 1;
  if (/MATE/.test(rule)) return `${subject} ${singular ? "allows" : "allow"} ${witness}`;
  if (/PROMOTION/.test(rule)) return `${subject} cannot stop ${witness}`;
  if (/RECAPTURE|FORCED-TRADE/.test(rule)) return `${subject} ${singular ? "is" : "are"} met by ${witness}`;
  if (/GAIN-CLAMP/.test(rule)) return `${subject} ${singular ? "does" : "do"} not challenge the secured gain`;
  if (/WIN-WITH-CHECK/.test(rule)) return `${subject} ${singular ? "leaves" : "leave"} ${witness} available with check`;
  if (/MATING-NET/.test(rule)) return `${subject} ${singular ? "remains" : "remain"} inside the mating net`;
  if (witness && !/^the (named|declared|available|secured)/i.test(witness)) return `${subject} ${singular ? "allows" : "allow"} ${witness}`;
  return `${subject} ${singular ? "is" : "are"} closed by the same one-ply tactical witness`;
}

function replySentences(node) {
  const replies = node?.replies || [];
  const preferred = preferredReply(node);
  const lines = [];
  const live = replies.filter((reply) => reply.live);
  for (const reply of live) lines.push(liveReplySentence(reply, reply === preferred));

  const closed = replies.filter((reply) => !reply.live);
  if (closed.length) {
    const witnessGroups = new Map();
    for (const reply of closed) {
      const key = `${reply.closure?.rule || ""}|${reply.closure?.witness || ""}`;
      if (!witnessGroups.has(key)) witnessGroups.set(key, []);
      witnessGroups.get(key).push(reply);
    }
    if (closed.length <= 2 && witnessGroups.size <= 2) {
      for (const group of witnessGroups.values()) lines.push(closedReplySentence({
        replies: group,
        rule: group[0]?.closure?.rule,
        witness: group[0]?.closure?.witness
      }, replies.length));
    } else {
      const f = node?.features || {};
      const mateWitness = dominantClosureWitness(node, (closure) => /MATE|MATING-NET/.test(closure.rule || "") || /#$/.test(closure.witness || ""));
      const tacticalWitness = dominantClosureWitness(node, (closure) => !/GAIN-CLAMP/.test(closure.rule || ""));
      if (f.mate || f.mate_threat || node?.terminal?.kind === "mate_threat" || node?.terminal?.kind === "policy_boundary") {
        lines.push(mateWitness ? `the other legal replies allow ${mateWitness}` : "the other legal replies remain inside the mating net");
      } else if (f.promotion || (node?.uses || []).includes("passed_pawn")) {
        lines.push("the other legal replies cannot stop the promotion sequence");
      } else if (f.attacks_queen || f.fork) {
        lines.push(tacticalWitness ? `the other legal replies leave ${tacticalWitness} available` : "the other legal replies do not remove the fork or queen attack");
      } else if (f.check) {
        lines.push(tacticalWitness ? `the other check answers leave ${tacticalWitness} available` : "the other check answers abandon the tactical target");
      } else if (f.capture) {
        lines.push("the other legal replies either decline the recapture or leave the material target gone");
      } else {
        lines.push("the other legal replies are closed by the same forcing-clamp witness");
      }
    }
  }
  return unique(lines).slice(0, 4);
}

export function generateTrace(result, metadata = {}) {
  const proof = result?.proof;
  const terminal = terminalOf(proof);
  const lines = [
    "CTT/1",
    `id: ${metadata.id || "predicate-chess-generated"}`,
    `fen: ${result?.fen || metadata.fen || ""}`,
    `objective: ${terminal?.label || metadata.objective || "find a forcing tactical win"}`,
    `status: ${proof?.proved ? "solved" : "inconclusive"}`,
    `main: ${proof?.node?.move?.san || ""}`,
    `positions_entered: ${result?.tryCount ?? 0}`,
    "",
    "[trace]",
    ""
  ];

  function walk(node) {
    if (!node) return;
    lines.push("THINK OBSERVE.");
    const predicates = relevantPredicateLines(node);
    lines.push(`SAW ${predicates.join("; ") || "the predicates used by the forcing move"}.`);
    lines.push(`CANDIDATES ${node.move.san}: ${onePlyPredicates(node).join(", ")}; USES=[${(node.uses || []).join(",")}].`);
    lines.push(`TRY ${node.move.san} BECAUSE ${node.rule}.`);
    if (node.replies?.length) {
      lines.push(`THINK REPLIES(goal=${node.terminal?.kind || "forcing objective"}).`);
      lines.push(...traceReplyLines(node));
      const liveReplies = node.replies.filter((reply) => reply.live && reply.child?.proved);
      liveReplies.forEach((reply, index) => {
        lines.push(`TRY ${reply.move.san} BECAUSE ALL-REPLIES: it is a LIVE defense.`);
        walk(reply.child?.node);
        if (index < liveReplies.length - 1) lines.push(`FROM ${reply.move.san} :: defeated within the policy boundary.`);
      });
    }
  }

  if (proof?.proved) {
    walk(proof.node);
    lines.push("PROVED.");
  } else {
    lines.push(`GIVEUP. ${proof?.reason || "The policy boundary was reached without a proof."}`);
  }
  return lines.join("\n");
}

export function generatePlainEnglish(result) {
  const proof = result?.proof;
  if (!proof?.proved) {
    return `OBSERVE\n  the solver could not complete a bounded proof\n\nGIVEUP\n  ${proof?.reason || "the policy boundary was reached"}`;
  }
  const blocks = [];
  function walk(node) {
    if (!node) return;
    const materialConversion = node.terminal?.kind === "material";
    const skipConversionObservations = materialConversion && !node.features?.capture;
    const observations = skipConversionObservations ? [] : observationSentences(node);
    if (observations.length) blocks.push(`OBSERVE\n${observations.map((line) => `  ${line}`).join("\n")}`);
    blocks.push(`${actionHeading(node)}\n  ${actionSentence(node)}`);

    // The CTT audits every reply. The training summary stops once a concrete
    // material conversion is established, rather than reciting incidental
    // closure witnesses after the human conclusion is already clear.
    if (materialConversion) {
      blocks.push("PROVED");
      return;
    }

    if (node.replies?.length) {
      const replies = replySentences(node);
      if (replies.length) blocks.push(`REPLIES\n${replies.map((line) => `  ${line}`).join("\n")}`);
      walk(preferredReply(node)?.child?.node);
    }
    if (node.terminal) blocks.push("PROVED");
  }
  walk(proof.node);
  return blocks.join("\n\n");
}

export function explainSolve(result, metadata = {}) {
  return {
    trace: generateTrace(result, metadata),
    plainEnglish: generatePlainEnglish(result),
    finalPgn: result?.finalPgn || ""
  };
}

export function parsePgnMoveTokens(pgn) {
  const movetext = String(pgn || "")
    .replace(/^\s*\[[^\n]*\]\s*$/gm, " ")
    .replace(/\{[^}]*\}/g, " ")
    .replace(/;[^\n]*/g, " ")
    .replace(/\$\d+/g, " ")
    .replace(/\b(?:1-0|0-1|1\/2-1\/2|\*)\b/g, " ")
    .replace(/\d+\.(?:\.\.)?/g, " ")
    .replace(/\.\.\./g, " ")
    .replace(/[()]/g, (match) => ` ${match} `)
    .trim();
  return movetext.split(/\s+/).filter(Boolean);
}
